swagger: "2.0"
info:
  title: pt backend
  version: "1.0"
  contact:
    name: pt backend authentication service
    url: https://pt-backend.rdeid.unil.ch
    email: development.bdsc@chuv.ch
tags:
  - name: AuthenticationService
  - name: IndexService
  - name: QuestionnaireService
  - name: UserService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/rest/v1/authentication/login:
    post:
      summary: Authenticate
      description: This endpoint authenticates a user
      operationId: AuthenticationService_Authenticate
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendAuthenticationReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendCredentials'
      tags:
        - Authentication
      x-openapi-router-controller: authentication_controller
  /api/rest/v1/users:
    post:
      summary: Create a user
      description: This endpoint creates a user
      operationId: UserService_CreateUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateUserReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendUser'
      tags:
        - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/me:
    get:
      summary: Get my own user
      description: This endpoint returns the details of the authenticated user
      operationId: UserService_GetUserMe
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetUserMeReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/me/password:
    put:
      summary: Update password
      description: This endpoint updates the password of the authenticated user
      operationId: UserService_UpdatePassword
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendUpdatePasswordReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendUpdatePasswordRequest'
      tags:
        - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/{id}:
    get:
      summary: Get a user
      description: This endpoint returns a user
      operationId: UserService_GetUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetUserReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - Users
      x-openapi-router-controller: user_controller
    delete:
      summary: Delete a user
      description: This endpoint deletes a user
      operationId: UserService_DeleteUser
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendDeleteUserReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/{id}/password/reset:
    post:
      summary: Reset password
      description: This endpoint resets a user's password
      operationId: UserService_ResetPassword
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendResetPasswordReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          required: true
          schema:
            type: object
      tags:
        - Users
      x-openapi-router-controller: user_controller
  /api/v1/hello:
    get:
      summary: Get a hello
      description: This endpoint returns a hello
      operationId: IndexService_GetHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetHelloReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Index
      x-openapi-router-controller: index_controller
  /api/v1/hello/{identifier}:
    post:
      summary: Get a hello
      description: This endpoint returns a hello
      operationId: IndexService_CreateHello
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateHelloReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: identifier
          in: path
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              title:
                type: string
              content:
                type: string
      tags:
        - Index
      x-openapi-router-controller: index_controller
  /api/v1/questionnaire:
    get:
      summary: List questionnaires
      description: This endpoint allows listing a user's questionnaires
      operationId: QuestionnaireService_ListQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendListQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: offset
          in: query
          required: false
          type: integer
          format: int64
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
      tags:
        - Questionnaire
      x-openapi-router-controller: questionnaire_controller
    post:
      summary: Create a questionnaire
      description: This endpoint creates a questionnaire
      operationId: QuestionnaireService_CreateQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireRequest'
      tags:
        - Questionnaire
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/{id}:
    get:
      summary: Get questionnaires
      description: This endpoint allow getting a single user's questionnaire
      operationId: QuestionnaireService_GetQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - Questionnaire
      x-openapi-router-controller: questionnaire_controller
    delete:
      summary: Create a questionnaire
      description: This endpoint creates a questionnaire
      operationId: QuestionnaireService_DeleteQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendDeleteQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - Questionnaire
      x-openapi-router-controller: questionnaire_controller
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  templatebackendAuthenticationReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendAuthenticationResult'
  templatebackendAuthenticationResult:
    type: object
    properties:
      token:
        type: string
  templatebackendCreateHelloReply:
    type: object
    properties:
      identifier:
        type: integer
        format: int32
      title:
        type: string
      content:
        type: string
  templatebackendCreateQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateQuestionnaireResult'
  templatebackendCreateQuestionnaireRequest:
    type: object
    properties:
      questionnaire:
        $ref: '#/definitions/templatebackendQuestionnaire'
    title: Message definitions for requests and responses
  templatebackendCreateQuestionnaireResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendCreateUserReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateUserResult'
    title: Create Users
  templatebackendCreateUserResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendCredentials:
    type: object
    properties:
      username:
        type: string
      password:
        type: string
      totp:
        type: string
  templatebackendDeleteQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendDeleteQuestionnaireResult'
  templatebackendDeleteQuestionnaireResult:
    type: object
    properties:
      success:
        type: boolean
  templatebackendDeleteUserReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendDeleteUserResult'
  templatebackendDeleteUserResult:
    type: object
  templatebackendGetHelloReply:
    type: object
    properties:
      content:
        type: string
  templatebackendGetQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetQuestionnaireResult'
  templatebackendGetQuestionnaireResult:
    type: object
    properties:
      questionnaire:
        $ref: '#/definitions/templatebackendQuestionnaire'
  templatebackendGetUserMeReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetUserMeResult'
  templatebackendGetUserMeResult:
    type: object
    properties:
      me:
        $ref: '#/definitions/templatebackendUser'
    title: Get User (me)
  templatebackendGetUserReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetUserResult'
  templatebackendGetUserResult:
    type: object
    properties:
      user:
        $ref: '#/definitions/templatebackendUser'
  templatebackendListQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendListQuestionnaireResult'
  templatebackendListQuestionnaireResult:
    type: object
    properties:
      questionnaires:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaire'
  templatebackendQuestionnaire:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      replyEditable:
        type: boolean
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireVersion'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 7;
  templatebackendQuestionnaireQuestion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      tab:
        type: string
      question:
        type: string
      riskWeight:
        type: integer
        format: int64
      answerType:
        type: string
      flag:
        type: string
      tooltip:
        type: string
      answers:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestionAnswer'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 11;
  templatebackendQuestionnaireQuestionAnswer:
    type: object
    properties:
      id:
        type: integer
        format: int64
      text:
        type: string
      riskLevel:
        type: integer
        format: int64
      rulePrefills:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestionAnswerRulePrefill'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 7;
  templatebackendQuestionnaireQuestionAnswerRulePrefill:
    type: object
    properties:
      id:
        type: integer
        format: int64
      questionId:
        type: integer
        format: int64
      answerId:
        type: integer
        format: int64
      answerText:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 7;
  templatebackendQuestionnaireVersion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      version:
        type: string
      questions:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestion'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 6;
  templatebackendResetPasswordReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendResetPasswordResult'
  templatebackendResetPasswordResult:
    type: object
  templatebackendUpdatePasswordReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendUpdateUserResult'
  templatebackendUpdatePasswordRequest:
    type: object
    properties:
      currentPassword:
        type: string
      newPassword:
        type: string
    title: Update User Password
  templatebackendUpdateUserResult:
    type: object
  templatebackendUser:
    type: object
    properties:
      id:
        type: integer
        format: int64
      firstName:
        type: string
      lastName:
        type: string
      username:
        type: string
      email:
        type: string
      password:
        type: string
      status:
        type: string
      roles:
        type: array
        items:
          type: string
      totpEnabled:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
      passwordChanged:
        type: boolean
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
  - {}
