# coding: utf-8

"""
    template backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.templatebackend_delete_medication_reply import TemplatebackendDeleteMedicationReply

class TestTemplatebackendDeleteMedicationReply(unittest.TestCase):
    """TemplatebackendDeleteMedicationReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatebackendDeleteMedicationReply:
        """Test TemplatebackendDeleteMedicationReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendDeleteMedicationReply`
        """
        model = TemplatebackendDeleteMedicationReply()
        if include_optional:
            return TemplatebackendDeleteMedicationReply(
                result = openapi_client.models.templatebackend_delete_medication_result.templatebackendDeleteMedicationResult(
                    success = True, )
            )
        else:
            return TemplatebackendDeleteMedicationReply(
        )
        """

    def testTemplatebackendDeleteMedicationReply(self):
        """Test TemplatebackendDeleteMedicationReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
