# coding: utf-8

"""
    template backend authentication service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development@taurusgroup.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.templatebackend_create_hello_reply import TemplatebackendCreateHelloReply  # noqa: E501
from openapi_client.rest import ApiException

class TestTemplatebackendCreateHelloReply(unittest.TestCase):
    """TemplatebackendCreateHelloReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TemplatebackendCreateHelloReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendCreateHelloReply`
        """
        model = openapi_client.models.templatebackend_create_hello_reply.TemplatebackendCreateHelloReply()  # noqa: E501
        if include_optional :
            return TemplatebackendCreateHelloReply(
                identifier = 56, 
                title = '', 
                content = ''
            )
        else :
            return TemplatebackendCreateHelloReply(
        )
        """

    def testTemplatebackendCreateHelloReply(self):
        """Test TemplatebackendCreateHelloReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
