# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_audit_log import V1AuditLog

class TestV1AuditLog(unittest.TestCase):
    """V1AuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1AuditLog:
        """Test V1AuditLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1AuditLog`
        """
        model = V1AuditLog()
        if include_optional:
            return V1AuditLog(
                id = 56,
                userid = 56,
                service = '',
                action = '',
                body = '',
                response = '',
                created_at = '',
                error = True
            )
        else:
            return V1AuditLog(
        )
        """

    def testV1AuditLog(self):
        """Test V1AuditLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
