# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.templatebackend_list_replies_reply import TemplatebackendListRepliesReply

class TestTemplatebackendListRepliesReply(unittest.TestCase):
    """TemplatebackendListRepliesReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatebackendListRepliesReply:
        """Test TemplatebackendListRepliesReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendListRepliesReply`
        """
        model = TemplatebackendListRepliesReply()
        if include_optional:
            return TemplatebackendListRepliesReply(
                result = openapi_client.models.templatebackend_list_replies_result.templatebackendListRepliesResult(
                    replies = [
                        openapi_client.models.templatebackend_questionnaire_reply.templatebackendQuestionnaireReply(
                            id = 56, 
                            questionnaire_version_id = 56, 
                            created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                            updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                        ], )
            )
        else:
            return TemplatebackendListRepliesReply(
        )
        """

    def testTemplatebackendListRepliesReply(self):
        """Test TemplatebackendListRepliesReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
