# coding: utf-8

"""
    template backend authentication service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development@taurusgroup.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

import openapi_client
from openapi_client.models.templatebackend_create_user_reply import TemplatebackendCreateUserReply  # noqa: E501
from openapi_client.rest import ApiException

class TestTemplatebackendCreateUserReply(unittest.TestCase):
    """TemplatebackendCreateUserReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test TemplatebackendCreateUserReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendCreateUserReply`
        """
        model = openapi_client.models.templatebackend_create_user_reply.TemplatebackendCreateUserReply()  # noqa: E501
        if include_optional :
            return TemplatebackendCreateUserReply(
                result = openapi_client.models.templatebackend_create_user_result.templatebackendCreateUserResult(
                    id = '', )
            )
        else :
            return TemplatebackendCreateUserReply(
        )
        """

    def testTemplatebackendCreateUserReply(self):
        """Test TemplatebackendCreateUserReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
