# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.templatebackend_share_reply_reply import TemplatebackendShareReplyReply

class TestTemplatebackendShareReplyReply(unittest.TestCase):
    """TemplatebackendShareReplyReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatebackendShareReplyReply:
        """Test TemplatebackendShareReplyReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendShareReplyReply`
        """
        model = TemplatebackendShareReplyReply()
        if include_optional:
            return TemplatebackendShareReplyReply(
                result = openapi_client.models.templatebackend_share_reply_result.templatebackendShareReplyResult(
                    success = True, )
            )
        else:
            return TemplatebackendShareReplyReply(
        )
        """

    def testTemplatebackendShareReplyReply(self):
        """Test TemplatebackendShareReplyReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
