# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.users_service_api import UsersServiceApi


class TestUsersServiceApi(unittest.TestCase):
    """UsersServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UsersServiceApi()

    def tearDown(self) -> None:
        pass

    def test_users_service_create_user(self) -> None:
        """Test case for users_service_create_user

        Create a user
        """
        pass

    def test_users_service_delete_user(self) -> None:
        """Test case for users_service_delete_user

        Delete a user
        """
        pass

    def test_users_service_get_user(self) -> None:
        """Test case for users_service_get_user

        Get a user
        """
        pass

    def test_users_service_get_user_me(self) -> None:
        """Test case for users_service_get_user_me

        Get my own user
        """
        pass

    def test_users_service_reset_password(self) -> None:
        """Test case for users_service_reset_password

        Reset password
        """
        pass

    def test_users_service_update_password(self) -> None:
        """Test case for users_service_update_password

        Update password
        """
        pass


if __name__ == '__main__':
    unittest.main()
