# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.questionnaire_service_share_reply_request import QuestionnaireServiceShareReplyRequest

class TestQuestionnaireServiceShareReplyRequest(unittest.TestCase):
    """QuestionnaireServiceShareReplyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> QuestionnaireServiceShareReplyRequest:
        """Test QuestionnaireServiceShareReplyRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `QuestionnaireServiceShareReplyRequest`
        """
        model = QuestionnaireServiceShareReplyRequest()
        if include_optional:
            return QuestionnaireServiceShareReplyRequest(
                sharedwith_userid = 56
            )
        else:
            return QuestionnaireServiceShareReplyRequest(
        )
        """

    def testQuestionnaireServiceShareReplyRequest(self):
        """Test QuestionnaireServiceShareReplyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
