# coding: utf-8

"""
    template backend authentication service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

import openapi_client
from openapi_client.api.index_api import IndexApi  # noqa: E501
from openapi_client.rest import ApiException


class TestIndexApi(unittest.TestCase):
    """IndexApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.index_api.IndexApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_index_service_create_hello(self):
        """Test case for index_service_create_hello

        Get a hello  # noqa: E501
        """
        pass

    def test_index_service_get_hello(self):
        """Test case for index_service_get_hello

        Get a hello  # noqa: E501
        """
        pass

    def test_index_service_get_helloo(self):
        """Test case for index_service_get_helloo

        Get a hello  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
