# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.v1_get_logs_response import V1GetLogsResponse

class TestV1GetLogsResponse(unittest.TestCase):
    """V1GetLogsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> V1GetLogsResponse:
        """Test V1GetLogsResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `V1GetLogsResponse`
        """
        model = V1GetLogsResponse()
        if include_optional:
            return V1GetLogsResponse(
                logs = [
                    openapi_client.models.v1_audit_log.v1AuditLog(
                        id = 56, 
                        userid = 56, 
                        service = '', 
                        action = '', 
                        body = '', 
                        response = '', 
                        created_at = '', 
                        error = True, )
                    ]
            )
        else:
            return V1GetLogsResponse(
        )
        """

    def testV1GetLogsResponse(self):
        """Test V1GetLogsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
