# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.questionnaire_api import QuestionnaireApi


class TestQuestionnaireApi(unittest.TestCase):
    """QuestionnaireApi unit test stubs"""

    def setUp(self) -> None:
        self.api = QuestionnaireApi()

    def tearDown(self) -> None:
        pass

    def test_questionnaire_service_create_questionnaire(self) -> None:
        """Test case for questionnaire_service_create_questionnaire

        Create a questionnaire
        """
        pass

    def test_questionnaire_service_delete_questionnaire(self) -> None:
        """Test case for questionnaire_service_delete_questionnaire

        Create a questionnaire
        """
        pass

    def test_questionnaire_service_get_questionnaire(self) -> None:
        """Test case for questionnaire_service_get_questionnaire

        Get questionnaires
        """
        pass

    def test_questionnaire_service_get_reply(self) -> None:
        """Test case for questionnaire_service_get_reply

        Get a questionnaires reply
        """
        pass

    def test_questionnaire_service_list_questionnaire(self) -> None:
        """Test case for questionnaire_service_list_questionnaire

        List questionnaires
        """
        pass

    def test_questionnaire_service_list_replies(self) -> None:
        """Test case for questionnaire_service_list_replies

        List questionnaires replies
        """
        pass


if __name__ == '__main__':
    unittest.main()
