# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.templatebackend_create_medication_request import TemplatebackendCreateMedicationRequest

class TestTemplatebackendCreateMedicationRequest(unittest.TestCase):
    """TemplatebackendCreateMedicationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatebackendCreateMedicationRequest:
        """Test TemplatebackendCreateMedicationRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendCreateMedicationRequest`
        """
        model = TemplatebackendCreateMedicationRequest()
        if include_optional:
            return TemplatebackendCreateMedicationRequest(
                medication = openapi_client.models.templatebackend_medication.templatebackendMedication(
                    id = 56, 
                    user_id = 56, 
                    name = '', 
                    dosage = '', 
                    frequency = '', 
                    created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                    updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
            )
        else:
            return TemplatebackendCreateMedicationRequest(
        )
        """

    def testTemplatebackendCreateMedicationRequest(self):
        """Test TemplatebackendCreateMedicationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
