# coding: utf-8

"""
    pt backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development.bdsc@chuv.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.templatebackend_audit_log import TemplatebackendAuditLog

class TestTemplatebackendAuditLog(unittest.TestCase):
    """TemplatebackendAuditLog unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> TemplatebackendAuditLog:
        """Test TemplatebackendAuditLog
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `TemplatebackendAuditLog`
        """
        model = TemplatebackendAuditLog()
        if include_optional:
            return TemplatebackendAuditLog(
                id = 56,
                userid = 56,
                service = '',
                action = '',
                body = '',
                response = '',
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                error = True
            )
        else:
            return TemplatebackendAuditLog(
        )
        """

    def testTemplatebackendAuditLog(self):
        """Test TemplatebackendAuditLog"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
