apiVersion: v2
name: pt-backend-chart
description: A Helm chart to deploy the backend of the Privacy Toolbox (RDeId) project.
type: application

# Helm Chart version
version: 0.1.0

# Application version
appVersion: "v0.1.1"

dependencies:
- name: postgresql
  version: "15.x.x"
  repository: "https://charts.bitnami.com/bitnami"
- name: jupyterhub-chart
  alias: jupyterhub
  version: "0.1.0"
  condition: jupyterhub.enabled
  tags:
    - jupyterhub
    - back-end
- name: pt-arx-service-chart
  alias: arx
  version: "0.1.0"
  condition: arx.enabled
  tags:
    - arx-service
    - back-end