"""NOTE: Autogenerated. Do not edit the manually."""

import connexion
from typing import Dict
from typing import Tuple
from typing import Union
from inspect import getmembers, isfunction


from server_template.models.rpc_status import RpcStatus
from server_template.models.templatebackend_authentication_reply import TemplatebackendAuthenticationReply
from server_template.models.templatebackend_credentials import TemplatebackendCredentials
from server_template import util

from src.internal.api.controllers import authentication_controller
controller_functions =  [func_tupple[0] for func_tupple in getmembers(authentication_controller, isfunction)]
needed_functions = ["authentication_service_authenticate"]
for op in needed_functions:
    if op not in controller_functions:
        raise NotImplementedError("operation " + op + " is not implemented by src.internal.api.controllers.authentication_controller")


def authentication_service_authenticate(body: TemplatebackendCredentials):
    """Authenticate

    This endpoint authenticates a user

    :param body: 
    :type body: dict | bytes

    :rtype: Union[TemplatebackendAuthenticationReply, Tuple[TemplatebackendAuthenticationReply, int], Tuple[TemplatebackendAuthenticationReply, int, Dict[str, str]]
    """
    if connexion.request.is_json:
        body = TemplatebackendCredentials.from_dict(connexion.request.get_json())

    return authentication_controller.authentication_service_authenticate(body)
