apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-backend-{{ include "chart.nameid" . }}
  labels:
    app: deployment-backend-{{ include "chart.nameid" . }}
    nameid: {{ include "chart.nameid" . }}
    version: {{ .Values.version }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-backend-{{ include "chart.nameid" . }}
  template:
    metadata:
      labels:
        app: deployment-backend-{{ include "chart.nameid" . }}
    spec:
      containers:
      - name: deployment-backend-{{ include "chart.nameid" . }}
        image: {{ .Values.image }}
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: backend-config
          mountPath: /pt_backend/conf
        command: ["python3"]
        args: ["-m", "src.cmd.start", "--config", "/pt_backend/conf/config.yaml"]
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
{{- if .Values.deployment.hostPath }}
        volumeMounts:
        - name: pt-backend-data
          mountPath: /var/lib/postgresql/data
{{- end }}
        env:
        - name: POSTGRES_USER
          value: admin
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_DB
          value: pt_backend
      imagePullSecrets:
      - name: registry-auth
      volumes:
      - name: backend-config
        secret:
          secretName: backend-config-{{ include "chart.nameid" . }}
          items:
          - key: config.yaml
            path: config.yaml
{{- if .Values.deployment.hostPath }}
      - name: pt-backend-data
        hostPath:
          path: {{ .Values.deployment.hostPath }}
{{- end }}