apiVersion: v1
kind: Service
metadata:
  name: ds-cicd-template-backend
spec:
  selector:
    app: ds-cicd-template-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP