apiVersion: v1
kind: Service
metadata:
  name: service-backend-{{ include "chart.nameid" . }}
  labels:
    version: {{ .Values.version }}
    nameid: {{ include "chart.nameid" . }}
spec:
  selector:
    app: service-backend-{{ include "chart.nameid" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP