apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
data:
  config.yaml: | 
    {{- mergeOverwrite (fromYaml (.Files.Get "main.yaml")) .Values.configOverride | toYaml | nindent 4 }}
