apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
data:
  config.yaml: | 
    {{- toYaml (mergeOverwrite .Values.config .Values.configOverride) | nindent 4  }}