apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
data:
  config.yaml: | 
    {{- tpl (.Files.Get "files/main.yaml") .Values.configOverride | nindent 4 }}