apiVersion: v1
kind: Secret
metadata:
  name: backend-config-secret
  labels:
    nameid: {{ include "pt-backend.nameid" . }}
    version: {{ .Values.version }}
type: Opaque
data:
  config.yaml: {{ include "pt-backend.main" . | b64enc }}