apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pt-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pt-backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}-deployment
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port | default 5000 }}
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-config-volume
              mountPath: "/pt_backend/conf"
            {{- if .Values.persistence.enabled }}
            - name: {{ .Release.Name }}-data
              mountPath: "/data/pt_backend"
            {{- end }}
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: pt-backend-secrets
                  key: jwt-secret
            - name: ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pt-backend-secrets
                  key: admin-token
            - name: SYMMETRIC_KEY
              valueFrom:
                secretKeyRef:
                  name: pt-backend-secrets
                  key: symmetric-encryption-key
          command:
            - python3
            - -m 
            - src.cmd.start
            - --config
            - "/pt_backend/conf/config.yaml"
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: {{ .Release.Name }}-config-volume
          configMap:
            name: {{ .Release.Name }}-configmap
        {{- if .Values.persistence.enabled }}
        - name: {{ .Release.Name }}-data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-pvc
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
