apiVersion: v1
kind: Secret
metadata:
  name: psql-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace "psql-secret" ) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $postgresPassword := (get $secretData "postgres-assword") | default (randAlphaNum 16 | b64enc) }}
  postgres-password: {{ $postgresPassword }}
