{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-pvc
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pt-backend.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
spec:
  accessModes:
    - {{ .Values.persistence.accessMode | default "ReadWriteOnce" }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | default "2Gi" }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | default "microk8s-hostpath"}}
  {{- end }}
{{- end }}