# coding: utf-8

"""
    Api Documentation

    Api Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, ClassVar, Dict, List, Optional
from pydantic import BaseModel, StrictInt, StrictStr
from pydantic import Field
from openapi_client.models.attribute_types import AttributeTypes
from openapi_client.models.risks import Risks
from openapi_client.models.statistics import Statistics
try:
    from typing import Self
except ImportError:
    from typing_extensions import Self

class Record(BaseModel):
    """
    Record
    """ # noqa: E501
    attribute_types: Optional[AttributeTypes] = Field(default=None, alias="attributeTypes")
    id: Optional[StrictInt] = None
    job_date: Optional[StrictStr] = Field(default=None, alias="jobDate")
    job_type: Optional[StrictStr] = Field(default=None, alias="jobType")
    nb_columns: Optional[StrictInt] = Field(default=None, alias="nbColumns")
    nb_rows: Optional[StrictInt] = Field(default=None, alias="nbRows")
    risks: Optional[Risks] = None
    statistics: Optional[Statistics] = None
    __properties: ClassVar[List[str]] = ["attributeTypes", "id", "jobDate", "jobType", "nbColumns", "nbRows", "risks", "statistics"]

    model_config = {
        "populate_by_name": True,
        "validate_assignment": True,
        "protected_namespaces": (),
    }


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Record from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        _dict = self.model_dump(
            by_alias=True,
            exclude={
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of attribute_types
        if self.attribute_types:
            _dict['attributeTypes'] = self.attribute_types.to_dict()
        # override the default output from pydantic by calling `to_dict()` of risks
        if self.risks:
            _dict['risks'] = self.risks.to_dict()
        # override the default output from pydantic by calling `to_dict()` of statistics
        if self.statistics:
            _dict['statistics'] = self.statistics.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Dict) -> Self:
        """Create an instance of Record from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attributeTypes": AttributeTypes.from_dict(obj.get("attributeTypes")) if obj.get("attributeTypes") is not None else None,
            "id": obj.get("id"),
            "jobDate": obj.get("jobDate"),
            "jobType": obj.get("jobType"),
            "nbColumns": obj.get("nbColumns"),
            "nbRows": obj.get("nbRows"),
            "risks": Risks.from_dict(obj.get("risks")) if obj.get("risks") is not None else None,
            "statistics": Statistics.from_dict(obj.get("statistics")) if obj.get("statistics") is not None else None
        })
        return _obj


