"""NOTE: Autogenerated. Do not edit the manually."""

import datetime
import inspect
import typing
from typing import get_type_hints
from server_template import typing_utils


def _deserialize(data, klass):
    """Deserializes dict, list, str into an object.

    :param data: dict, list or str.
    :param klass: class literal, or string of class name.

    :return: object.
    """
    if data is None:
        return None

    if klass in (int, float, str, bool, bytearray):
        return _deserialize_primitive(data, klass)
    elif klass == object:
        return _deserialize_object(data)
    elif klass == datetime.date:
        return deserialize_date(data)
    elif klass == datetime.datetime:
        return deserialize_datetime(data)
    elif typing_utils.is_generic(klass):
        if typing_utils.is_list(klass):
            return _deserialize_list(data, klass.__args__[0])
        if typing_utils.is_dict(klass):
            return _deserialize_dict(data, klass.__args__[1])
    else:
        return deserialize_model(data, klass)


def _deserialize_primitive(data, klass):
    """Deserializes to primitive type.

    :param data: data to deserialize.
    :param klass: class literal.

    :return: int, long, float, str, bool.
    :rtype: int | long | float | str | bool
    """
    try:
        value = klass(data)
    except UnicodeEncodeError:
        value = data
    except TypeError:
        value = data
    return value


def _deserialize_object(value):
    """Return an original value.

    :return: object.
    """
    return value


def deserialize_date(string):
    """Deserializes string to date.

    :param string: str.
    :type string: str
    :return: date.
    :rtype: date
    """
    if string is None:
      return None
    
    try:
        from dateutil.parser import parse
        return parse(string).date()
    except ImportError:
        return string


def deserialize_datetime(string):
    """Deserializes string to datetime.

    The string should be in iso8601 datetime format.

    :param string: str.
    :type string: str
    :return: datetime.
    :rtype: datetime
    """
    if string is None:
      return None
    
    try:
        from dateutil.parser import parse
        return parse(string)
    except ImportError:
        return string


def deserialize_model(data, klass):
    """Deserializes list or dict to model.

    :param data: dict, list.
    :type data: dict | list
    :param klass: class literal.
    :return: model object.
    """
    instance = klass()

    if not instance.openapi_types:
        return data

    for attr, attr_type in instance.openapi_types.items():
        if data is not None \
                and instance.attribute_map[attr] in data \
                and isinstance(data, (list, dict)):
            value = data[instance.attribute_map[attr]]
            setattr(instance, attr, _deserialize(value, attr_type))

    return instance


def _deserialize_list(data, boxed_type):
    """Deserializes a list and its elements.

    :param data: list to deserialize.
    :type data: list
    :param boxed_type: class literal.

    :return: deserialized list.
    :rtype: list
    """
    return [_deserialize(sub_data, boxed_type)
            for sub_data in data]


def _deserialize_dict(data, boxed_type):
    """Deserializes a dict and its elements.

    :param data: dict to deserialize.
    :type data: dict
    :param boxed_type: class literal.

    :return: deserialized dict.
    :rtype: dict
    """
    return {k: _deserialize(v, boxed_type)
            for k, v in data.items() }

def get_method_signature(obj):
    cls = obj if inspect.isclass(obj) else type(obj)
    signatures = {}
    for member_name, member in inspect.getmembers(cls, predicate=inspect.isfunction):
        if not member_name.startswith('_'):
            signatures[member_name] = (inspect.signature(member), get_type_hints(member))
    return signatures

def implements_interface(A, B):
    a_signatures = get_method_signature(A)
    b_signatures = get_method_signature(B)

    for op, (a_signature, a_type_hints) in a_signatures.items():
        if op not in b_signatures:
            raise NotImplementedError(f"operation {op} is not implemented by provided controller")
        
        b_signature, b_type_hints = b_signatures[op]

        # Check if all parameters are present and have correct types
        for param_name, param in a_signature.parameters.items():
            if param_name not in b_signature.parameters:
                raise NotImplementedError(f"operation {op} is missing parameter {param_name}")

            # Check type hints
            a_param_type = a_type_hints.get(param_name)
            b_param_type = b_type_hints.get(param_name)
            if a_param_type is not None and a_param_type != b_param_type:
                raise NotImplementedError(f"operation {op} parameter {param_name} does not have the correct type")

        # Check for extra parameters in B that are not in A
        for param_name in b_signature.parameters:
            if param_name not in a_signature.parameters:
                raise NotImplementedError(f"operation {op} in provided controller has an extra parameter {param_name}")

        # Check return type
        if 'return' in a_type_hints and 'return' in b_type_hints and a_type_hints['return'] != b_type_hints['return']:
            raise NotImplementedError(f"operation {op} has an incorrect return type")
        
        print("op", op, a_signature, a_type_hints, b_signature, b_type_hints)

