####################################
# jupyterhub chart configuration
####################################

# This is to override the chart name.
nameOverride: "jupyterhub"
fullnameOverride: ""

# This will set the replicaset count.
replicaCount: 1

# This sets the container image.
image:
  repository: registry.rdeid.unil.ch/jupyterhub
  pullPolicy: IfNotPresent
  tag: "latest"
  pullSecrets:
    - name: registry-auth

# This is for setting up a service.
service:
  enabled: true
  type: ClusterIP
  port: 8000

# This block is for setting up the ingress.
ingress:
  enabled: true
  host: jupyterhub-test.rdeid.unil.ch
  tls: true # Secret name should match: {{ .Chart.Name }}-tls
  className: public
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"

# Specific env variable for the container.
env:
  # Allowed domains within jupyterhub iFrame
  allowedFrameDomains: "https://pt-frontend-test.rdeid.unil.ch" # Space separated list
  
# Deployment specific options
podAnnotations: {}
podLabels: {}
affinity: {}
tolerations: []
nodeSelector: {}
resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi