"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_get_user_me_result import TemplatebackendGetUserMeResult
from server_template import util

from server_template.models.templatebackend_get_user_me_result import TemplatebackendGetUserMeResult

class TemplatebackendGetUserMeReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendGetUserMeReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendGetUserMeReply.
        :type result: TemplatebackendGetUserMeResult
        """
        self.openapi_types = {
            'result': TemplatebackendGetUserMeResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendGetUserMeReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendGetUserMeReply of this TemplatebackendGetUserMeReply.
        :rtype: TemplatebackendGetUserMeReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendGetUserMeResult:
        """Gets the result of this TemplatebackendGetUserMeReply.


        :return: The result of this TemplatebackendGetUserMeReply.
        :rtype: TemplatebackendGetUserMeResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendGetUserMeResult):
        """Sets the result of this TemplatebackendGetUserMeReply.


        :param result: The result of this TemplatebackendGetUserMeReply.
        :type result: TemplatebackendGetUserMeResult
        """

        self._result = result
