"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template import util


class TemplatebackendAuditLog(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, userid=None, service=None, action=None, body=None, response=None, created_at=None, error=None):
        """TemplatebackendAuditLog - a model defined in OpenAPI

        :param id: The id of this TemplatebackendAuditLog.
        :type id: int
        :param userid: The userid of this TemplatebackendAuditLog.
        :type userid: int
        :param service: The service of this TemplatebackendAuditLog.
        :type service: str
        :param action: The action of this TemplatebackendAuditLog.
        :type action: str
        :param body: The body of this TemplatebackendAuditLog.
        :type body: str
        :param response: The response of this TemplatebackendAuditLog.
        :type response: str
        :param created_at: The created_at of this TemplatebackendAuditLog.
        :type created_at: datetime
        :param error: The error of this TemplatebackendAuditLog.
        :type error: bool
        """
        self.openapi_types = {
            'id': int,
            'userid': int,
            'service': str,
            'action': str,
            'body': str,
            'response': str,
            'created_at': datetime,
            'error': bool
        }

        self.attribute_map = {
            'id': 'id',
            'userid': 'userid',
            'service': 'service',
            'action': 'action',
            'body': 'body',
            'response': 'response',
            'created_at': 'createdAt',
            'error': 'error'
        }

        self._id = id
        self._userid = userid
        self._service = service
        self._action = action
        self._body = body
        self._response = response
        self._created_at = created_at
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendAuditLog':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendAuditLog of this TemplatebackendAuditLog.
        :rtype: TemplatebackendAuditLog
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this TemplatebackendAuditLog.


        :return: The id of this TemplatebackendAuditLog.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this TemplatebackendAuditLog.


        :param id: The id of this TemplatebackendAuditLog.
        :type id: int
        """

        self._id = id

    @property
    def userid(self) -> int:
        """Gets the userid of this TemplatebackendAuditLog.


        :return: The userid of this TemplatebackendAuditLog.
        :rtype: int
        """
        return self._userid

    @userid.setter
    def userid(self, userid: int):
        """Sets the userid of this TemplatebackendAuditLog.


        :param userid: The userid of this TemplatebackendAuditLog.
        :type userid: int
        """

        self._userid = userid

    @property
    def service(self) -> str:
        """Gets the service of this TemplatebackendAuditLog.


        :return: The service of this TemplatebackendAuditLog.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this TemplatebackendAuditLog.


        :param service: The service of this TemplatebackendAuditLog.
        :type service: str
        """

        self._service = service

    @property
    def action(self) -> str:
        """Gets the action of this TemplatebackendAuditLog.


        :return: The action of this TemplatebackendAuditLog.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this TemplatebackendAuditLog.


        :param action: The action of this TemplatebackendAuditLog.
        :type action: str
        """

        self._action = action

    @property
    def body(self) -> str:
        """Gets the body of this TemplatebackendAuditLog.


        :return: The body of this TemplatebackendAuditLog.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this TemplatebackendAuditLog.


        :param body: The body of this TemplatebackendAuditLog.
        :type body: str
        """

        self._body = body

    @property
    def response(self) -> str:
        """Gets the response of this TemplatebackendAuditLog.


        :return: The response of this TemplatebackendAuditLog.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this TemplatebackendAuditLog.


        :param response: The response of this TemplatebackendAuditLog.
        :type response: str
        """

        self._response = response

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this TemplatebackendAuditLog.


        :return: The created_at of this TemplatebackendAuditLog.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this TemplatebackendAuditLog.


        :param created_at: The created_at of this TemplatebackendAuditLog.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def error(self) -> bool:
        """Gets the error of this TemplatebackendAuditLog.


        :return: The error of this TemplatebackendAuditLog.
        :rtype: bool
        """
        return self._error

    @error.setter
    def error(self, error: bool):
        """Sets the error of this TemplatebackendAuditLog.


        :param error: The error of this TemplatebackendAuditLog.
        :type error: bool
        """

        self._error = error
