"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_list_replies_result import TemplatebackendListRepliesResult
from server_template import util

from server_template.models.templatebackend_list_replies_result import TemplatebackendListRepliesResult

class TemplatebackendListRepliesReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendListRepliesReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendListRepliesReply.
        :type result: TemplatebackendListRepliesResult
        """
        self.openapi_types = {
            'result': TemplatebackendListRepliesResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendListRepliesReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendListRepliesReply of this TemplatebackendListRepliesReply.
        :rtype: TemplatebackendListRepliesReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendListRepliesResult:
        """Gets the result of this TemplatebackendListRepliesReply.


        :return: The result of this TemplatebackendListRepliesReply.
        :rtype: TemplatebackendListRepliesResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendListRepliesResult):
        """Sets the result of this TemplatebackendListRepliesReply.


        :param result: The result of this TemplatebackendListRepliesReply.
        :type result: TemplatebackendListRepliesResult
        """

        self._result = result
