"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_transform_config import TemplatebackendTransformConfig
from server_template import util

from server_template.models.templatebackend_transform_config import TemplatebackendTransformConfig

class TemplatebackendCreateTransformConfigRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, config=None):
        """TemplatebackendCreateTransformConfigRequest - a model defined in OpenAPI

        :param config: The config of this TemplatebackendCreateTransformConfigRequest.
        :type config: TemplatebackendTransformConfig
        """
        self.openapi_types = {
            'config': TemplatebackendTransformConfig
        }

        self.attribute_map = {
            'config': 'config'
        }

        self._config = config

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendCreateTransformConfigRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendCreateTransformConfigRequest of this TemplatebackendCreateTransformConfigRequest.
        :rtype: TemplatebackendCreateTransformConfigRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def config(self) -> TemplatebackendTransformConfig:
        """Gets the config of this TemplatebackendCreateTransformConfigRequest.


        :return: The config of this TemplatebackendCreateTransformConfigRequest.
        :rtype: TemplatebackendTransformConfig
        """
        return self._config

    @config.setter
    def config(self, config: TemplatebackendTransformConfig):
        """Sets the config of this TemplatebackendCreateTransformConfigRequest.


        :param config: The config of this TemplatebackendCreateTransformConfigRequest.
        :type config: TemplatebackendTransformConfig
        """

        self._config = config
