"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_user_email import TemplatebackendUserEmail
from server_template import util

from server_template.models.templatebackend_user_email import TemplatebackendUserEmail

class TemplatebackendSearchUsersReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendSearchUsersReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendSearchUsersReply.
        :type result: List[TemplatebackendUserEmail]
        """
        self.openapi_types = {
            'result': List[TemplatebackendUserEmail]
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendSearchUsersReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendSearchUsersReply of this TemplatebackendSearchUsersReply.
        :rtype: TemplatebackendSearchUsersReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> List[TemplatebackendUserEmail]:
        """Gets the result of this TemplatebackendSearchUsersReply.


        :return: The result of this TemplatebackendSearchUsersReply.
        :rtype: List[TemplatebackendUserEmail]
        """
        return self._result

    @result.setter
    def result(self, result: List[TemplatebackendUserEmail]):
        """Sets the result of this TemplatebackendSearchUsersReply.


        :param result: The result of this TemplatebackendSearchUsersReply.
        :type result: List[TemplatebackendUserEmail]
        """

        self._result = result
