"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_create_user_result import TemplatebackendCreateUserResult
from server_template import util

from server_template.models.templatebackend_create_user_result import TemplatebackendCreateUserResult

class TemplatebackendCreateUserReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendCreateUserReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendCreateUserReply.
        :type result: TemplatebackendCreateUserResult
        """
        self.openapi_types = {
            'result': TemplatebackendCreateUserResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendCreateUserReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendCreateUserReply of this TemplatebackendCreateUserReply.
        :rtype: TemplatebackendCreateUserReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendCreateUserResult:
        """Gets the result of this TemplatebackendCreateUserReply.


        :return: The result of this TemplatebackendCreateUserReply.
        :rtype: TemplatebackendCreateUserResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendCreateUserResult):
        """Sets the result of this TemplatebackendCreateUserReply.


        :param result: The result of this TemplatebackendCreateUserReply.
        :type result: TemplatebackendCreateUserResult
        """

        self._result = result
