"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_delete_config_result import TemplatebackendDeleteConfigResult
from server_template import util

from server_template.models.templatebackend_delete_config_result import TemplatebackendDeleteConfigResult

class TemplatebackendDeleteConfigReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendDeleteConfigReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendDeleteConfigReply.
        :type result: TemplatebackendDeleteConfigResult
        """
        self.openapi_types = {
            'result': TemplatebackendDeleteConfigResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendDeleteConfigReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendDeleteConfigReply of this TemplatebackendDeleteConfigReply.
        :rtype: TemplatebackendDeleteConfigReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendDeleteConfigResult:
        """Gets the result of this TemplatebackendDeleteConfigReply.


        :return: The result of this TemplatebackendDeleteConfigReply.
        :rtype: TemplatebackendDeleteConfigResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendDeleteConfigResult):
        """Sets the result of this TemplatebackendDeleteConfigReply.


        :param result: The result of this TemplatebackendDeleteConfigReply.
        :type result: TemplatebackendDeleteConfigResult
        """

        self._result = result
