"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_share_reply_result import TemplatebackendShareReplyResult
from server_template import util

from server_template.models.templatebackend_share_reply_result import TemplatebackendShareReplyResult

class TemplatebackendShareReplyReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendShareReplyReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendShareReplyReply.
        :type result: TemplatebackendShareReplyResult
        """
        self.openapi_types = {
            'result': TemplatebackendShareReplyResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendShareReplyReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendShareReplyReply of this TemplatebackendShareReplyReply.
        :rtype: TemplatebackendShareReplyReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendShareReplyResult:
        """Gets the result of this TemplatebackendShareReplyReply.


        :return: The result of this TemplatebackendShareReplyReply.
        :rtype: TemplatebackendShareReplyResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendShareReplyResult):
        """Sets the result of this TemplatebackendShareReplyReply.


        :param result: The result of this TemplatebackendShareReplyReply.
        :type result: TemplatebackendShareReplyResult
        """

        self._result = result
