"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_get_questionnaire_result import TemplatebackendGetQuestionnaireResult
from server_template import util

from server_template.models.templatebackend_get_questionnaire_result import TemplatebackendGetQuestionnaireResult

class TemplatebackendGetQuestionnaireReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendGetQuestionnaireReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendGetQuestionnaireReply.
        :type result: TemplatebackendGetQuestionnaireResult
        """
        self.openapi_types = {
            'result': TemplatebackendGetQuestionnaireResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendGetQuestionnaireReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendGetQuestionnaireReply of this TemplatebackendGetQuestionnaireReply.
        :rtype: TemplatebackendGetQuestionnaireReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendGetQuestionnaireResult:
        """Gets the result of this TemplatebackendGetQuestionnaireReply.


        :return: The result of this TemplatebackendGetQuestionnaireReply.
        :rtype: TemplatebackendGetQuestionnaireResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendGetQuestionnaireResult):
        """Sets the result of this TemplatebackendGetQuestionnaireReply.


        :param result: The result of this TemplatebackendGetQuestionnaireReply.
        :type result: TemplatebackendGetQuestionnaireResult
        """

        self._result = result
