"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_authentication_result import TemplatebackendAuthenticationResult
from server_template import util

from server_template.models.templatebackend_authentication_result import TemplatebackendAuthenticationResult

class TemplatebackendAuthenticationReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendAuthenticationReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendAuthenticationReply.
        :type result: TemplatebackendAuthenticationResult
        """
        self.openapi_types = {
            'result': TemplatebackendAuthenticationResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendAuthenticationReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendAuthenticationReply of this TemplatebackendAuthenticationReply.
        :rtype: TemplatebackendAuthenticationReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendAuthenticationResult:
        """Gets the result of this TemplatebackendAuthenticationReply.


        :return: The result of this TemplatebackendAuthenticationReply.
        :rtype: TemplatebackendAuthenticationResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendAuthenticationResult):
        """Sets the result of this TemplatebackendAuthenticationReply.


        :param result: The result of this TemplatebackendAuthenticationReply.
        :type result: TemplatebackendAuthenticationResult
        """

        self._result = result
