"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_questionnaire_reply import TemplatebackendQuestionnaireReply
from server_template import util

from server_template.models.templatebackend_questionnaire_reply import TemplatebackendQuestionnaireReply

class TemplatebackendCreateReplyRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reply=None):
        """TemplatebackendCreateReplyRequest - a model defined in OpenAPI

        :param reply: The reply of this TemplatebackendCreateReplyRequest.
        :type reply: TemplatebackendQuestionnaireReply
        """
        self.openapi_types = {
            'reply': TemplatebackendQuestionnaireReply
        }

        self.attribute_map = {
            'reply': 'reply'
        }

        self._reply = reply

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendCreateReplyRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendCreateReplyRequest of this TemplatebackendCreateReplyRequest.
        :rtype: TemplatebackendCreateReplyRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reply(self) -> TemplatebackendQuestionnaireReply:
        """Gets the reply of this TemplatebackendCreateReplyRequest.


        :return: The reply of this TemplatebackendCreateReplyRequest.
        :rtype: TemplatebackendQuestionnaireReply
        """
        return self._reply

    @reply.setter
    def reply(self, reply: TemplatebackendQuestionnaireReply):
        """Sets the reply of this TemplatebackendCreateReplyRequest.


        :param reply: The reply of this TemplatebackendCreateReplyRequest.
        :type reply: TemplatebackendQuestionnaireReply
        """

        self._reply = reply
