"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_create_config_result import TemplatebackendCreateConfigResult
from server_template import util

from server_template.models.templatebackend_create_config_result import TemplatebackendCreateConfigResult

class TemplatebackendCreateConfigReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendCreateConfigReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendCreateConfigReply.
        :type result: TemplatebackendCreateConfigResult
        """
        self.openapi_types = {
            'result': TemplatebackendCreateConfigResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendCreateConfigReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendCreateConfigReply of this TemplatebackendCreateConfigReply.
        :rtype: TemplatebackendCreateConfigReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendCreateConfigResult:
        """Gets the result of this TemplatebackendCreateConfigReply.


        :return: The result of this TemplatebackendCreateConfigReply.
        :rtype: TemplatebackendCreateConfigResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendCreateConfigResult):
        """Sets the result of this TemplatebackendCreateConfigReply.


        :param result: The result of this TemplatebackendCreateConfigReply.
        :type result: TemplatebackendCreateConfigResult
        """

        self._result = result
