"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_create_medication_result import TemplatebackendCreateMedicationResult
from server_template import util

from server_template.models.templatebackend_create_medication_result import TemplatebackendCreateMedicationResult

class TemplatebackendCreateMedicationReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendCreateMedicationReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendCreateMedicationReply.
        :type result: TemplatebackendCreateMedicationResult
        """
        self.openapi_types = {
            'result': TemplatebackendCreateMedicationResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendCreateMedicationReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendCreateMedicationReply of this TemplatebackendCreateMedicationReply.
        :rtype: TemplatebackendCreateMedicationReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendCreateMedicationResult:
        """Gets the result of this TemplatebackendCreateMedicationReply.


        :return: The result of this TemplatebackendCreateMedicationReply.
        :rtype: TemplatebackendCreateMedicationResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendCreateMedicationResult):
        """Sets the result of this TemplatebackendCreateMedicationReply.


        :param result: The result of this TemplatebackendCreateMedicationReply.
        :type result: TemplatebackendCreateMedicationResult
        """

        self._result = result
