"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template import util


class TemplatebackendUserEmail(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, email=None):
        """TemplatebackendUserEmail - a model defined in OpenAPI

        :param id: The id of this TemplatebackendUserEmail.
        :type id: int
        :param email: The email of this TemplatebackendUserEmail.
        :type email: str
        """
        self.openapi_types = {
            'id': int,
            'email': str
        }

        self.attribute_map = {
            'id': 'id',
            'email': 'email'
        }

        self._id = id
        self._email = email

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendUserEmail':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendUserEmail of this TemplatebackendUserEmail.
        :rtype: TemplatebackendUserEmail
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this TemplatebackendUserEmail.


        :return: The id of this TemplatebackendUserEmail.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this TemplatebackendUserEmail.


        :param id: The id of this TemplatebackendUserEmail.
        :type id: int
        """

        self._id = id

    @property
    def email(self) -> str:
        """Gets the email of this TemplatebackendUserEmail.


        :return: The email of this TemplatebackendUserEmail.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this TemplatebackendUserEmail.


        :param email: The email of this TemplatebackendUserEmail.
        :type email: str
        """

        self._email = email
