"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_get_medication_result import TemplatebackendGetMedicationResult
from server_template import util

from server_template.models.templatebackend_get_medication_result import TemplatebackendGetMedicationResult

class TemplatebackendGetMedicationReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):
        """TemplatebackendGetMedicationReply - a model defined in OpenAPI

        :param result: The result of this TemplatebackendGetMedicationReply.
        :type result: TemplatebackendGetMedicationResult
        """
        self.openapi_types = {
            'result': TemplatebackendGetMedicationResult
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendGetMedicationReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendGetMedicationReply of this TemplatebackendGetMedicationReply.
        :rtype: TemplatebackendGetMedicationReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self) -> TemplatebackendGetMedicationResult:
        """Gets the result of this TemplatebackendGetMedicationReply.


        :return: The result of this TemplatebackendGetMedicationReply.
        :rtype: TemplatebackendGetMedicationResult
        """
        return self._result

    @result.setter
    def result(self, result: TemplatebackendGetMedicationResult):
        """Sets the result of this TemplatebackendGetMedicationReply.


        :param result: The result of this TemplatebackendGetMedicationReply.
        :type result: TemplatebackendGetMedicationResult
        """

        self._result = result
