"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template import util


class TemplatebackendColumn(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, value=None):
        """TemplatebackendColumn - a model defined in OpenAPI

        :param value: The value of this TemplatebackendColumn.
        :type value: List[str]
        """
        self.openapi_types = {
            'value': List[str]
        }

        self.attribute_map = {
            'value': 'value'
        }

        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendColumn':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendColumn of this TemplatebackendColumn.
        :rtype: TemplatebackendColumn
        """
        return util.deserialize_model(dikt, cls)

    @property
    def value(self) -> List[str]:
        """Gets the value of this TemplatebackendColumn.


        :return: The value of this TemplatebackendColumn.
        :rtype: List[str]
        """
        return self._value

    @value.setter
    def value(self, value: List[str]):
        """Sets the value of this TemplatebackendColumn.


        :param value: The value of this TemplatebackendColumn.
        :type value: List[str]
        """

        self._value = value
