"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.templatebackend_questionnaire_question_reply import TemplatebackendQuestionnaireQuestionReply
from server_template import util

from server_template.models.templatebackend_questionnaire_question_reply import TemplatebackendQuestionnaireQuestionReply

class TemplatebackendQuestionnaireReply(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, questionnaire_question_id=None, replies=None, created_at=None, updated_at=None):
        """TemplatebackendQuestionnaireReply - a model defined in OpenAPI

        :param id: The id of this TemplatebackendQuestionnaireReply.
        :type id: int
        :param questionnaire_question_id: The questionnaire_question_id of this TemplatebackendQuestionnaireReply.
        :type questionnaire_question_id: int
        :param replies: The replies of this TemplatebackendQuestionnaireReply.
        :type replies: List[TemplatebackendQuestionnaireQuestionReply]
        :param created_at: The created_at of this TemplatebackendQuestionnaireReply.
        :type created_at: datetime
        :param updated_at: The updated_at of this TemplatebackendQuestionnaireReply.
        :type updated_at: datetime
        """
        self.openapi_types = {
            'id': int,
            'questionnaire_question_id': int,
            'replies': List[TemplatebackendQuestionnaireQuestionReply],
            'created_at': datetime,
            'updated_at': datetime
        }

        self.attribute_map = {
            'id': 'id',
            'questionnaire_question_id': 'questionnaireQuestionId',
            'replies': 'replies',
            'created_at': 'createdAt',
            'updated_at': 'updatedAt'
        }

        self._id = id
        self._questionnaire_question_id = questionnaire_question_id
        self._replies = replies
        self._created_at = created_at
        self._updated_at = updated_at

    @classmethod
    def from_dict(cls, dikt) -> 'TemplatebackendQuestionnaireReply':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The templatebackendQuestionnaireReply of this TemplatebackendQuestionnaireReply.
        :rtype: TemplatebackendQuestionnaireReply
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this TemplatebackendQuestionnaireReply.


        :return: The id of this TemplatebackendQuestionnaireReply.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this TemplatebackendQuestionnaireReply.


        :param id: The id of this TemplatebackendQuestionnaireReply.
        :type id: int
        """

        self._id = id

    @property
    def questionnaire_question_id(self) -> int:
        """Gets the questionnaire_question_id of this TemplatebackendQuestionnaireReply.


        :return: The questionnaire_question_id of this TemplatebackendQuestionnaireReply.
        :rtype: int
        """
        return self._questionnaire_question_id

    @questionnaire_question_id.setter
    def questionnaire_question_id(self, questionnaire_question_id: int):
        """Sets the questionnaire_question_id of this TemplatebackendQuestionnaireReply.


        :param questionnaire_question_id: The questionnaire_question_id of this TemplatebackendQuestionnaireReply.
        :type questionnaire_question_id: int
        """

        self._questionnaire_question_id = questionnaire_question_id

    @property
    def replies(self) -> List[TemplatebackendQuestionnaireQuestionReply]:
        """Gets the replies of this TemplatebackendQuestionnaireReply.


        :return: The replies of this TemplatebackendQuestionnaireReply.
        :rtype: List[TemplatebackendQuestionnaireQuestionReply]
        """
        return self._replies

    @replies.setter
    def replies(self, replies: List[TemplatebackendQuestionnaireQuestionReply]):
        """Sets the replies of this TemplatebackendQuestionnaireReply.


        :param replies: The replies of this TemplatebackendQuestionnaireReply.
        :type replies: List[TemplatebackendQuestionnaireQuestionReply]
        """

        self._replies = replies

    @property
    def created_at(self) -> datetime:
        """Gets the created_at of this TemplatebackendQuestionnaireReply.


        :return: The created_at of this TemplatebackendQuestionnaireReply.
        :rtype: datetime
        """
        return self._created_at

    @created_at.setter
    def created_at(self, created_at: datetime):
        """Sets the created_at of this TemplatebackendQuestionnaireReply.


        :param created_at: The created_at of this TemplatebackendQuestionnaireReply.
        :type created_at: datetime
        """

        self._created_at = created_at

    @property
    def updated_at(self) -> datetime:
        """Gets the updated_at of this TemplatebackendQuestionnaireReply.


        :return: The updated_at of this TemplatebackendQuestionnaireReply.
        :rtype: datetime
        """
        return self._updated_at

    @updated_at.setter
    def updated_at(self, updated_at: datetime):
        """Sets the updated_at of this TemplatebackendQuestionnaireReply.


        :param updated_at: The updated_at of this TemplatebackendQuestionnaireReply.
        :type updated_at: datetime
        """

        self._updated_at = updated_at
