"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template.models.v1_audit_log import V1AuditLog
from server_template import util

from server_template.models.v1_audit_log import V1AuditLog

class V1GetLogsResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, logs=None):
        """V1GetLogsResponse - a model defined in OpenAPI

        :param logs: The logs of this V1GetLogsResponse.
        :type logs: List[V1AuditLog]
        """
        self.openapi_types = {
            'logs': List[V1AuditLog]
        }

        self.attribute_map = {
            'logs': 'logs'
        }

        self._logs = logs

    @classmethod
    def from_dict(cls, dikt) -> 'V1GetLogsResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1GetLogsResponse of this V1GetLogsResponse.
        :rtype: V1GetLogsResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logs(self) -> List[V1AuditLog]:
        """Gets the logs of this V1GetLogsResponse.


        :return: The logs of this V1GetLogsResponse.
        :rtype: List[V1AuditLog]
        """
        return self._logs

    @logs.setter
    def logs(self, logs: List[V1AuditLog]):
        """Sets the logs of this V1GetLogsResponse.


        :param logs: The logs of this V1GetLogsResponse.
        :type logs: List[V1AuditLog]
        """

        self._logs = logs
