"""NOTE: Autogenerated. Do not edit the manually."""

from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server_template.models.base_model import Model
from server_template import util


class V1LogEventRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, userid=None, service=None, action=None, body=None, response=None, error=None):
        """V1LogEventRequest - a model defined in OpenAPI

        :param userid: The userid of this V1LogEventRequest.
        :type userid: int
        :param service: The service of this V1LogEventRequest.
        :type service: str
        :param action: The action of this V1LogEventRequest.
        :type action: str
        :param body: The body of this V1LogEventRequest.
        :type body: str
        :param response: The response of this V1LogEventRequest.
        :type response: str
        :param error: The error of this V1LogEventRequest.
        :type error: bool
        """
        self.openapi_types = {
            'userid': int,
            'service': str,
            'action': str,
            'body': str,
            'response': str,
            'error': bool
        }

        self.attribute_map = {
            'userid': 'userid',
            'service': 'service',
            'action': 'action',
            'body': 'body',
            'response': 'response',
            'error': 'error'
        }

        self._userid = userid
        self._service = service
        self._action = action
        self._body = body
        self._response = response
        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'V1LogEventRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The v1LogEventRequest of this V1LogEventRequest.
        :rtype: V1LogEventRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def userid(self) -> int:
        """Gets the userid of this V1LogEventRequest.


        :return: The userid of this V1LogEventRequest.
        :rtype: int
        """
        return self._userid

    @userid.setter
    def userid(self, userid: int):
        """Sets the userid of this V1LogEventRequest.


        :param userid: The userid of this V1LogEventRequest.
        :type userid: int
        """

        self._userid = userid

    @property
    def service(self) -> str:
        """Gets the service of this V1LogEventRequest.


        :return: The service of this V1LogEventRequest.
        :rtype: str
        """
        return self._service

    @service.setter
    def service(self, service: str):
        """Sets the service of this V1LogEventRequest.


        :param service: The service of this V1LogEventRequest.
        :type service: str
        """

        self._service = service

    @property
    def action(self) -> str:
        """Gets the action of this V1LogEventRequest.


        :return: The action of this V1LogEventRequest.
        :rtype: str
        """
        return self._action

    @action.setter
    def action(self, action: str):
        """Sets the action of this V1LogEventRequest.


        :param action: The action of this V1LogEventRequest.
        :type action: str
        """

        self._action = action

    @property
    def body(self) -> str:
        """Gets the body of this V1LogEventRequest.


        :return: The body of this V1LogEventRequest.
        :rtype: str
        """
        return self._body

    @body.setter
    def body(self, body: str):
        """Sets the body of this V1LogEventRequest.


        :param body: The body of this V1LogEventRequest.
        :type body: str
        """

        self._body = body

    @property
    def response(self) -> str:
        """Gets the response of this V1LogEventRequest.


        :return: The response of this V1LogEventRequest.
        :rtype: str
        """
        return self._response

    @response.setter
    def response(self, response: str):
        """Sets the response of this V1LogEventRequest.


        :param response: The response of this V1LogEventRequest.
        :type response: str
        """

        self._response = response

    @property
    def error(self) -> bool:
        """Gets the error of this V1LogEventRequest.


        :return: The error of this V1LogEventRequest.
        :rtype: bool
        """
        return self._error

    @error.setter
    def error(self, error: bool):
        """Sets the error of this V1LogEventRequest.


        :param error: The error of this V1LogEventRequest.
        :type error: bool
        """

        self._error = error
