daemon:
  title: "pt backend"
  http:
    host: localhost
    port: 5000
    headers:
      access_control_allow_origin: "*"
      access_control_max_age: "600"
  public_url: "https://pt-backend.rdeid.unil.ch"
  jwt:
    secret: "{{ .jwt_secret }}"
    expiration_time: 259200 # 72h
  jobs:
    job_status_gc:
      enabled: true
  private_key_file: ./configs/dev/files/keys/pt_backend_privkey.pem
  public_key_file: ./configs/dev/files/keys/pt_backend_pubkey.pem

clients:
  arx:
    host: "http://arx-service.arx:8080/"
  jupyterhub:
    host: "https://jupyterhub.rdeid.unil.ch/"
    admin_token: "{{ .jupyterhub_token }}"
    key: "{{ .jupyterhub_key }}"

storage:
  datastores:
    pt_backend:
      type: postgres
      driver: psycopg2
      migration_table_name: tt_migrations
      host: localhost
      port: 5432
      username: admin
      password: password
      database: pt_backend
      max_connections: 10
      max_lifetime: 10s
      debug_mode: true
      ssl:
        enabled: false
        certificate_file: /pt_backend/postgres-certs/client.crt
        key_file: /pt_backend/postgres-certs/client.key

services:
  index_service:
    key: value
  authentication_service:
    enabled: true
  mailer:
    smtp:
      user: smtpUser
      password: smtpPassword
      host: smtp-relay.sendinblue.com
      port: 587
      authentication: plain

log:
  loggers:
    stdout_technical:
      level: debug
    stdout_security:
      level: debug
    stdout_business:
      level: debug

steward:
  user:
    enabled: true
    username: admin
    password: astrongpassword
  questionnaire:
    enabled: true
    name: Test Jfrei - Questionnaire