apiVersion: v1
kind: Namespace
metadata:
  name: int

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pt-backend
  namespace: int
  labels:
    app: pt-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pt-backend
  template:
    metadata:
      labels:
        app: pt-backend
    spec:
      containers:
      - name: pt-backend
        image: registry.rdeid.unil.ch/pt-backend:latest
        ports:
        - containerPort: 3001
      imagePullSecrets:
      - name: registry-auth

---

apiVersion: v1
kind: Service
metadata:
  name: pt-backend
  namespace: int
spec:
  selector:
    app: pt-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3001
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pt-backend-ingress
  namespace: int
  annotations:
    kubernetes.io/ingress.class: "public"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 1024m
spec:
  tls:
  - hosts:
    - pt-backend.rdeid.unil.ch
    secretName: pt-backend-tls
  rules:
  - host: pt-backend.rdeid.unil.ch
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pt-backend
            port:
              number: 80
