"""NOTE: Autogenerated. Do not edit the manually."""

import unittest

from flask import json

from server_template.models.rpc_status import RpcStatus
from server_template.models.templatebackend_get_config_reply import TemplatebackendGetConfigReply
from server_template.test import BaseTestCase


class TestConfigurationController(BaseTestCase):
    """ConfigurationController integration test stubs"""

    def test_config_service_get_config(self):
        """Test case for config_service_get_config

        Get a configuration file
        """
        headers = { 
            'Accept': 'application/json',
            'Bearer': 'special-key',
        }
        response = self.client.open(
            '/api/rest/v1/configs/{id}'.format(id=56),
            method='GET',
            headers=headers)
        self.assert200(response,
                       'Response body is : ' + response.data.decode('utf-8'))


if __name__ == '__main__':
    unittest.main()
