"""NOTE: Autogenerated. Do not edit the manually."""

import unittest

from flask import json

from server_template.models.rpc_status import RpcStatus
from server_template.models.templatebackend_authentication_reply import TemplatebackendAuthenticationReply
from server_template.models.templatebackend_credentials import TemplatebackendCredentials
from server_template.test import BaseTestCase


class TestAuthenticationServiceController(BaseTestCase):
    """AuthenticationServiceController integration test stubs"""

    def test_authentication_service_authenticate(self):
        """Test case for authentication_service_authenticate

        Authenticate
        """
        body = server_template.TemplatebackendCredentials()
        headers = { 
            'Accept': 'application/json',
            'Content-Type': 'application/json',
            'Bearer': 'special-key',
        }
        response = self.client.open(
            '/api/rest/v1/authentication/login',
            method='POST',
            headers=headers,
            data=json.dumps(body),
            content_type='application/json')
        self.assert200(response,
                       'Response body is : ' + response.data.decode('utf-8'))


if __name__ == '__main__':
    unittest.main()
