version: '3'
name: pt-backend-dev-container
services:
  pt_backend:
    build:
      context: ..
      dockerfile: docker/dockerfiles/dev.dockerfile
    volumes:
      - ..:/workspace:cached
      # - /run/docker.sock:/run/docker.sock
    command: /bin/sh -c "while sleep 1000; do :; done"
    user: root
  postgres:
    image: postgres
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pt_backend
