swagger: "2.0"
info:
  title: pt backend
  version: "1.0"
  contact:
    name: pt backend configuration for sphn service
    url: https://pt-backend.rdeid.unil.ch
    email: development.bdsc@chuv.ch
tags:
  - name: ConfigService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/rest/v1/configs:
    get:
      summary: Get configuration files
      description: This endpoint returns the configuration files for a given user
      operationId: ConfigService_GetConfigs
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetConfigsReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      tags:
        - Configuration
      x-openapi-router-controller: config_generator_controller
    post:
      summary: Create a configuration
      description: This endpoint creates a usconfigurationer
      operationId: ConfigService_CreateConfig
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateConfigReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendConfig'
      tags:
        - Configuration
      x-openapi-router-controller: config_generator_controller
  /api/v1/config/{id}:
    delete:
      summary: Deletes a config
      description: This endpoint deletes a config
      operationId: ConfigService_DeleteConfig
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendDeleteConfigReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - Configuration
      x-openapi-router-controller: config_generator_controller
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  templatebackendConfig:
    type: object
    properties:
      id:
        type: integer
        format: int64
      userid:
        type: integer
        format: int64
      tenantid:
        type: integer
        format: int64
      configName:
        type: string
      questionnaireid:
        type: integer
        format: int64
      hasScrambleField:
        type: boolean
      hasDateShift:
        type: boolean
      hassubFieldList:
        type: boolean
      hassubFieldRegex:
        type: boolean
      scrambleFieldFields:
        type: array
        items:
          type: string
      dateShiftLowrange:
        type: integer
        format: int32
      dateShiftHighrange:
        type: integer
        format: int32
      subFieldListField:
        type: string
      subFieldListSubstitute:
        type: array
        items:
          type: string
      subFieldListReplacement:
        type: string
      subFieldRegexField:
        type: string
      subFieldRegexRegex:
        type: string
      subFieldRegexReplacement:
        type: string
      createdAt:
        type: string
        format: date-time
      deletedAt:
        type: string
        format: date-time
  templatebackendCreateConfigReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateConfigResult'
  templatebackendCreateConfigResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendDeleteConfigReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendDeleteConfigResult'
  templatebackendDeleteConfigResult:
    type: object
    properties:
      success:
        type: boolean
  templatebackendGetConfigsReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetConfigsResult'
  templatebackendGetConfigsResult:
    type: object
    properties:
      config:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendConfig'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
  - {}
