swagger: "2.0"
info:
  title: template backend
  version: "1.0"
  contact:
    name: template backend questionnaire service
    url: https://gitlab.itrcs3-app.intranet.chuv/datascience/ds-template-backend
    email: dev@chuv.ch
tags:
  - name: QuestionnaireService
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /api/v1/questionnaire:
    get:
      summary: List questionnaires
      description: This endpoint allows listing a user's questionnaires
      operationId: QuestionnaireService_ListQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendListQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: offset
          in: query
          required: false
          type: integer
          format: int64
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
    post:
      summary: Create a questionnaire
      description: This endpoint creates a questionnaire
      operationId: QuestionnaireService_CreateQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireRequest'
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/replies:
    get:
      summary: List questionnaires replies
      description: This endpoint allows listing a user's questionnaires replies
      operationId: QuestionnaireService_ListReplies
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendListRepliesReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: offset
          description: uint32 questionnaire_version_id = 1;
          in: query
          required: false
          type: integer
          format: int64
        - name: limit
          in: query
          required: false
          type: integer
          format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
    post:
      summary: Create questionnaires reply
      description: This endpoint allows ceating a user's questionnaires reply
      operationId: QuestionnaireService_CreateReply
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateReplyReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendCreateReplyRequest'
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/replies/{id}:
    get:
      summary: Get a questionnaires reply
      description: This endpoint allows getting a user's questionnaires reply
      operationId: QuestionnaireService_GetReply
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetReplyReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          description: uint32 questionnaire_version_id = 1;
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
    delete:
      summary: Delete a questionnaires reply
      description: This endpoint allows to delete a questionnaire reply
      operationId: QuestionnaireService_DeleteReply
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendDeleteReplyReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/replies/{id}/share:
    post:
      summary: Share questionnaires reply
      description: This endpoint allows sharing a user's questionnaires reply
      operationId: QuestionnaireService_ShareReply
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendShareReplyReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
        - name: body
          in: body
          required: true
          schema:
            type: object
            properties:
              sharedwithUserid:
                type: integer
                format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/version:
    post:
      summary: Create a questionnaire version
      description: This endpoint creates a questionnaire version
      operationId: QuestionnaireService_CreateQuestionnaireVersion
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireVersionReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/templatebackendCreateQuestionnaireVersionRequest'
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
  /api/v1/questionnaire/{id}:
    get:
      summary: Get questionnaires
      description: This endpoint allow getting a single user's questionnaire
      operationId: QuestionnaireService_GetQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendGetQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: integer
          format: int64
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
    delete:
      summary: Delete a questionnaire
      description: This endpoint allows to delete a questionnaire
      operationId: QuestionnaireService_DeleteQuestionnaire
      responses:
        "200":
          description: A successful response.
          schema:
            $ref: '#/definitions/templatebackendDeleteQuestionnaireReply'
        default:
          description: An unexpected error response.
          schema:
            $ref: '#/definitions/rpcStatus'
      parameters:
        - name: id
          in: path
          required: true
          type: string
      tags:
        - QuestionnaireService
      x-openapi-router-controller: questionnaire_controller
definitions:
  protobufAny:
    type: object
    properties:
      '@type':
        type: string
    additionalProperties: {}
  rpcStatus:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      details:
        type: array
        items:
          type: object
          $ref: '#/definitions/protobufAny'
  templatebackendCreateQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateQuestionnaireResult'
  templatebackendCreateQuestionnaireRequest:
    type: object
    properties:
      questionnaire:
        $ref: '#/definitions/templatebackendQuestionnaire'
    title: Message definitions for requests and responses
  templatebackendCreateQuestionnaireResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendCreateQuestionnaireVersionReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateQuestionnaireVersionResult'
  templatebackendCreateQuestionnaireVersionRequest:
    type: object
    properties:
      id:
        type: integer
        format: int64
      version:
        $ref: '#/definitions/templatebackendQuestionnaireVersion'
    title: Message definitions for requests and responses
  templatebackendCreateQuestionnaireVersionResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendCreateReplyReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendCreateReplyResult'
  templatebackendCreateReplyRequest:
    type: object
    properties:
      reply:
        $ref: '#/definitions/templatebackendQuestionnaireReply'
  templatebackendCreateReplyResult:
    type: object
    properties:
      id:
        type: integer
        format: int64
  templatebackendDeleteQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendDeleteQuestionnaireResult'
  templatebackendDeleteQuestionnaireResult:
    type: object
    properties:
      success:
        type: boolean
  templatebackendDeleteReplyReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendDeleteReplyResult'
  templatebackendDeleteReplyResult:
    type: object
    properties:
      success:
        type: boolean
  templatebackendGetQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetQuestionnaireResult'
  templatebackendGetQuestionnaireResult:
    type: object
    properties:
      questionnaire:
        $ref: '#/definitions/templatebackendQuestionnaire'
  templatebackendGetReplyReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendGetReplyResult'
  templatebackendGetReplyResult:
    type: object
    properties:
      reply:
        $ref: '#/definitions/templatebackendQuestionnaireReply'
  templatebackendListQuestionnaireReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendListQuestionnaireResult'
  templatebackendListQuestionnaireResult:
    type: object
    properties:
      questionnaires:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaire'
  templatebackendListRepliesReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendListRepliesResult'
  templatebackendListRepliesResult:
    type: object
    properties:
      replies:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireReply'
  templatebackendQuestionnaire:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      replyEditable:
        type: boolean
      lastVersion:
        type: string
      versions:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireVersion'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 7;
  templatebackendQuestionnaireQuestion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      tab:
        type: string
      question:
        type: string
      riskWeight:
        type: integer
        format: int64
      answerType:
        type: string
      flag:
        type: string
      tooltip:
        type: string
      tmpUUID:
        type: string
        title: |-
          to be used for rule prefills as the id of the question
          is still unknown at the time of creation
          this will be used by the backend to compute the id but will not be
          stored in the database
      answers:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestionAnswer'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 12;
  templatebackendQuestionnaireQuestionAnswer:
    type: object
    properties:
      id:
        type: integer
        format: int64
      text:
        type: string
      riskLevel:
        type: integer
        format: int64
      highRisk:
        type: boolean
      tmpUUID:
        type: string
        title: |-
          to be used for rule prefills as the id of the answer
          is still unknown at the time of creation
          this will be used by the backend to compute the id but will not be
          stored in the database
      JSONConfiguration:
        type: string
      rulePrefills:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestionAnswerRulePrefill'
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 8;
  templatebackendQuestionnaireQuestionAnswerRulePrefill:
    type: object
    properties:
      id:
        type: integer
        format: int64
      questionId:
        type: integer
        format: int64
      answerId:
        type: integer
        format: int64
      answerText:
        type: string
      tmpQuestionUUID:
        type: string
      tmpAnswerUUID:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 9;
  templatebackendQuestionnaireQuestionReply:
    type: object
    properties:
      id:
        type: integer
        format: int64
      questionnaireQuestionId:
        type: integer
        format: int64
      answer:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 7;
  templatebackendQuestionnaireReply:
    type: object
    properties:
      id:
        type: integer
        format: int64
      questionnaireVersionId:
        type: integer
        format: int64
      projectName:
        type: string
      replies:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestionReply'
      userId:
        type: integer
        format: int64
      userName:
        type: string
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 11;
  templatebackendQuestionnaireVersion:
    type: object
    properties:
      id:
        type: integer
        format: int64
      version:
        type: string
      questions:
        type: array
        items:
          type: object
          $ref: '#/definitions/templatebackendQuestionnaireQuestion'
      published:
        type: boolean
      createdAt:
        type: string
        format: date-time
      updatedAt:
        type: string
        format: date-time
        title: google.protobuf.Timestamp deletedAt = 6;
  templatebackendShareReplyReply:
    type: object
    properties:
      result:
        $ref: '#/definitions/templatebackendShareReplyResult'
  templatebackendShareReplyResult:
    type: object
    properties:
      success:
        type: boolean
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
security:
  - Bearer: []
  - {}
