# coding: utf-8

"""
    Api Documentation

    Api Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.attribute_types import AttributeTypes

class TestAttributeTypes(unittest.TestCase):
    """AttributeTypes unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AttributeTypes:
        """Test AttributeTypes
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AttributeTypes`
        """
        model = AttributeTypes()
        if include_optional:
            return AttributeTypes(
                quasi_identifying = [
                    ''
                    ],
                sensitive = [
                    ''
                    ]
            )
        else:
            return AttributeTypes(
        )
        """

    def testAttributeTypes(self):
        """Test AttributeTypes"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
