# coding: utf-8

"""
    Api Documentation

    Api Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.deidentification_api_api import DeidentificationApiApi


class TestDeidentificationApiApi(unittest.TestCase):
    """DeidentificationApiApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeidentificationApiApi()

    def tearDown(self) -> None:
        pass

    def test_apply_expert_by_average_prosecutor_risk_level_using_post(self) -> None:
        """Test case for apply_expert_by_average_prosecutor_risk_level_using_post

        applyExpertByAverageProsecutorRiskLevel
        """
        pass

    def test_apply_expert_by_highest_prosecutor_risk_level_using_post(self) -> None:
        """Test case for apply_expert_by_highest_prosecutor_risk_level_using_post

        applyExpertByHighestProsecutorRiskLevel
        """
        pass

    def test_apply_expert_by_marketer_risk_level_using_post(self) -> None:
        """Test case for apply_expert_by_marketer_risk_level_using_post

        applyExpertByMarketerRiskLevel
        """
        pass

    def test_apply_expert_by_privacy_models_using_post(self) -> None:
        """Test case for apply_expert_by_privacy_models_using_post

        applyExpertByPrivacyModels
        """
        pass

    def test_apply_expert_internal_chuv_context_using_post(self) -> None:
        """Test case for apply_expert_internal_chuv_context_using_post

        applyExpertInternalCHUVContext
        """
        pass

    def test_apply_expert_multicentric_context_using_post(self) -> None:
        """Test case for apply_expert_multicentric_context_using_post

        applyExpertMulticentricContext
        """
        pass

    def test_apply_expert_publication_context_using_post(self) -> None:
        """Test case for apply_expert_publication_context_using_post

        applyExpertPublicationContext
        """
        pass

    def test_apply_safe_harbor_using_post(self) -> None:
        """Test case for apply_safe_harbor_using_post

        applySafeHarbor
        """
        pass

    def test_code_using_post(self) -> None:
        """Test case for code_using_post

        code
        """
        pass

    def test_decode_using_post(self) -> None:
        """Test case for decode_using_post

        decode
        """
        pass


if __name__ == '__main__':
    unittest.main()
