# coding: utf-8

"""
    Api Documentation

    Api Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.statistics import Statistics

class TestStatistics(unittest.TestCase):
    """Statistics unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Statistics:
        """Test Statistics
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Statistics`
        """
        model = Statistics()
        if include_optional:
            return Statistics(
                aecs_quality = 1.337,
                discernibility_quality = 1.337,
                levels = [
                    56
                    ],
                privacy_models = [
                    ''
                    ],
                suppressed_rows = 1.337
            )
        else:
            return Statistics(
        )
        """

    def testStatistics(self):
        """Test Statistics"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
