# coding: utf-8

"""
    Api Documentation

    Api Documentation

    The version of the OpenAPI document: 1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.record import Record

class TestRecord(unittest.TestCase):
    """Record unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Record:
        """Test Record
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Record`
        """
        model = Record()
        if include_optional:
            return Record(
                attribute_types = openapi_client.models.attribute_types.AttributeTypes(
                    quasi_identifying = [
                        ''
                        ], 
                    sensitive = [
                        ''
                        ], ),
                id = 56,
                job_date = '',
                job_type = '',
                nb_columns = 56,
                nb_rows = 56,
                risks = openapi_client.models.risks.Risks(
                    expected_average_prosecutor = 1.337, 
                    expected_highest_prosecutor = 1.337, 
                    expected_marketer = 1.337, 
                    initial_average_prosecutor = 1.337, 
                    initial_highest_prosecutor = 1.337, 
                    initial_marketer = 1.337, 
                    residual_average_prosecutor = 1.337, 
                    residual_highest_prosecutor = 1.337, 
                    residual_marketer = 1.337, ),
                statistics = openapi_client.models.statistics.Statistics(
                    aecs_quality = 1.337, 
                    discernibility_quality = 1.337, 
                    levels = [
                        56
                        ], 
                    privacy_models = [
                        ''
                        ], 
                    suppressed_rows = 1.337, )
            )
        else:
            return Record(
        )
        """

    def testRecord(self):
        """Test Record"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
