openapi: 3.0.1
info:
  contact:
    email: development.bdsc@chuv.ch
    name: pt backend authentication service
    url: https://pt-backend.rdeid.unil.ch
  title: pt backend
  version: "1.0"
servers:
- url: /
security:
- Bearer: []
- {}
tags:
- name: AuthenticationService
- name: IndexService
- name: UserService
paths:
  /api/rest/v1/authentication/login:
    post:
      description: This endpoint authenticates a user
      operationId: authentication_service_authenticate
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/templatebackendCredentials'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendAuthenticationReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Authenticate
      tags:
      - Authentication
      x-openapi-router-controller: authentication_controller
      x-codegen-request-body-name: body
  /api/rest/v1/users:
    post:
      description: This endpoint creates a user
      operationId: user_service_create_user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/templatebackendUser'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendCreateUserReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Create a user
      tags:
      - Users
      x-openapi-router-controller: user_controller
      x-codegen-request-body-name: body
  /api/rest/v1/users/me:
    get:
      description: This endpoint returns the details of the authenticated user
      operationId: user_service_get_user_me
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendGetUserMeReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Get my own user
      tags:
      - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/me/password:
    put:
      description: This endpoint updates the password of the authenticated user
      operationId: user_service_update_password
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/templatebackendUpdatePasswordRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendUpdatePasswordReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Update password
      tags:
      - Users
      x-openapi-router-controller: user_controller
      x-codegen-request-body-name: body
  /api/rest/v1/users/{id}:
    delete:
      description: This endpoint deletes a user
      operationId: user_service_delete_user
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendDeleteUserReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Delete a user
      tags:
      - Users
      x-openapi-router-controller: user_controller
    get:
      description: This endpoint returns a user
      operationId: user_service_get_user
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendGetUserReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Get a user
      tags:
      - Users
      x-openapi-router-controller: user_controller
  /api/rest/v1/users/{id}/password/reset:
    post:
      description: This endpoint resets a user's password
      operationId: user_service_reset_password
      parameters:
      - in: path
        name: id
        required: true
        schema:
          format: int64
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendResetPasswordReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Reset password
      tags:
      - Users
      x-openapi-router-controller: user_controller
      x-codegen-request-body-name: body
  /api/v1/hello:
    get:
      description: This endpoint returns a hello
      operationId: index_service_get_hello
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendGetHelloReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Get a hello
      tags:
      - Index
      x-openapi-router-controller: index_controller
  /api/v1/hello/{identifier}:
    post:
      description: This endpoint returns a hello
      operationId: index_service_create_hello
      parameters:
      - in: path
        name: identifier
        required: true
        schema:
          format: int32
          type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/IndexService_CreateHello_request'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/templatebackendCreateHelloReply'
          description: A successful response.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/rpcStatus'
          description: An unexpected error response.
      summary: Get a hello
      tags:
      - Index
      x-openapi-router-controller: index_controller
      x-codegen-request-body-name: body
components:
  schemas:
    protobufAny:
      additionalProperties:
        type: object
      properties:
        '@type':
          type: string
      title: protobufAny
      type: object
    rpcStatus:
      properties:
        code:
          format: int32
          title: code
          type: integer
        message:
          title: message
          type: string
        details:
          items:
            $ref: '#/components/schemas/protobufAny'
          title: details
          type: array
      title: rpcStatus
      type: object
    templatebackendAuthenticationReply:
      example:
        result:
          token: token
      properties:
        result:
          $ref: '#/components/schemas/templatebackendAuthenticationResult'
      title: templatebackendAuthenticationReply
      type: object
    templatebackendAuthenticationResult:
      example:
        token: token
      properties:
        token:
          title: token
          type: string
      title: templatebackendAuthenticationResult
      type: object
    templatebackendCreateHelloReply:
      example:
        identifier: 0
        title: title
        content: content
      properties:
        identifier:
          format: int32
          title: identifier
          type: integer
        title:
          title: title
          type: string
        content:
          title: content
          type: string
      title: templatebackendCreateHelloReply
      type: object
    templatebackendCreateUserReply:
      example:
        result:
          id: 0
      properties:
        result:
          $ref: '#/components/schemas/templatebackendCreateUserResult'
      title: Create Users
      type: object
    templatebackendCreateUserResult:
      example:
        id: 0
      properties:
        id:
          format: int64
          title: id
          type: integer
      title: templatebackendCreateUserResult
      type: object
    templatebackendCredentials:
      properties:
        username:
          title: username
          type: string
        password:
          title: password
          type: string
        totp:
          title: totp
          type: string
      title: templatebackendCredentials
      type: object
    templatebackendDeleteUserReply:
      example:
        result: "{}"
      properties:
        result:
          title: result
          type: object
      title: templatebackendDeleteUserReply
      type: object
    templatebackendDeleteUserResult:
      title: result
      type: object
    templatebackendGetHelloReply:
      example:
        content: content
      properties:
        content:
          title: content
          type: string
      title: templatebackendGetHelloReply
      type: object
    templatebackendGetUserMeReply:
      example:
        result:
          me:
            firstName: firstName
            lastName: lastName
            createdAt: 2000-01-23T04:56:07.000+00:00
            password: password
            passwordChanged: true
            roles:
            - roles
            - roles
            id: 0
            totpEnabled: true
            email: email
            username: username
            status: status
            updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        result:
          $ref: '#/components/schemas/templatebackendGetUserMeResult'
      title: templatebackendGetUserMeReply
      type: object
    templatebackendGetUserMeResult:
      example:
        me:
          firstName: firstName
          lastName: lastName
          createdAt: 2000-01-23T04:56:07.000+00:00
          password: password
          passwordChanged: true
          roles:
          - roles
          - roles
          id: 0
          totpEnabled: true
          email: email
          username: username
          status: status
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        me:
          $ref: '#/components/schemas/templatebackendUser'
      title: Get User (me)
      type: object
    templatebackendGetUserReply:
      example:
        result:
          user:
            firstName: firstName
            lastName: lastName
            createdAt: 2000-01-23T04:56:07.000+00:00
            password: password
            passwordChanged: true
            roles:
            - roles
            - roles
            id: 0
            totpEnabled: true
            email: email
            username: username
            status: status
            updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        result:
          $ref: '#/components/schemas/templatebackendGetUserResult'
      title: templatebackendGetUserReply
      type: object
    templatebackendGetUserResult:
      example:
        user:
          firstName: firstName
          lastName: lastName
          createdAt: 2000-01-23T04:56:07.000+00:00
          password: password
          passwordChanged: true
          roles:
          - roles
          - roles
          id: 0
          totpEnabled: true
          email: email
          username: username
          status: status
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        user:
          $ref: '#/components/schemas/templatebackendUser'
      title: templatebackendGetUserResult
      type: object
    templatebackendResetPasswordReply:
      example:
        result: "{}"
      properties:
        result:
          title: result
          type: object
      title: templatebackendResetPasswordReply
      type: object
    templatebackendResetPasswordResult:
      title: result
      type: object
    templatebackendUpdatePasswordReply:
      example:
        result: "{}"
      properties:
        result:
          title: result
          type: object
      title: templatebackendUpdatePasswordReply
      type: object
    templatebackendUpdatePasswordRequest:
      properties:
        currentPassword:
          title: currentPassword
          type: string
        newPassword:
          title: newPassword
          type: string
      title: Update User Password
      type: object
    templatebackendUpdateUserResult:
      title: result
      type: object
    templatebackendUser:
      example:
        firstName: firstName
        lastName: lastName
        createdAt: 2000-01-23T04:56:07.000+00:00
        password: password
        passwordChanged: true
        roles:
        - roles
        - roles
        id: 0
        totpEnabled: true
        email: email
        username: username
        status: status
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          format: int64
          title: id
          type: integer
        firstName:
          title: firstName
          type: string
        lastName:
          title: lastName
          type: string
        username:
          title: username
          type: string
        email:
          title: email
          type: string
        password:
          title: password
          type: string
        status:
          title: status
          type: string
        roles:
          items:
            type: string
          title: roles
          type: array
        totpEnabled:
          title: totpEnabled
          type: boolean
        createdAt:
          format: date-time
          title: createdAt
          type: string
        updatedAt:
          format: date-time
          title: updatedAt
          type: string
        passwordChanged:
          title: passwordChanged
          type: boolean
      title: templatebackendUser
      type: object
    IndexService_CreateHello_request:
      properties:
        title:
          title: title
          type: string
        content:
          title: content
          type: string
      title: IndexService_CreateHello_request
      type: object
  securitySchemes:
    Bearer:
      in: header
      name: Authorization
      type: apiKey
      x-apikeyInfoFunc: server_template.controllers.security_controller.info_from_Bearer
x-original-swagger-version: "2.0"
