# coding: utf-8

# flake8: noqa
"""
    template backend authentication service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0
    Contact: development@taurusgroup.ch
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.index_service_create_hello_request import IndexServiceCreateHelloRequest
from openapi_client.models.protobuf_any import ProtobufAny
from openapi_client.models.rpc_status import RpcStatus
from openapi_client.models.templatebackend_authentication_reply import TemplatebackendAuthenticationReply
from openapi_client.models.templatebackend_authentication_result import TemplatebackendAuthenticationResult
from openapi_client.models.templatebackend_create_hello_reply import TemplatebackendCreateHelloReply
from openapi_client.models.templatebackend_create_user_reply import TemplatebackendCreateUserReply
from openapi_client.models.templatebackend_create_user_result import TemplatebackendCreateUserResult
from openapi_client.models.templatebackend_credentials import TemplatebackendCredentials
from openapi_client.models.templatebackend_delete_user_reply import TemplatebackendDeleteUserReply
from openapi_client.models.templatebackend_get_hello_reply import TemplatebackendGetHelloReply
from openapi_client.models.templatebackend_get_user_me_reply import TemplatebackendGetUserMeReply
from openapi_client.models.templatebackend_get_user_me_result import TemplatebackendGetUserMeResult
from openapi_client.models.templatebackend_get_user_reply import TemplatebackendGetUserReply
from openapi_client.models.templatebackend_get_user_result import TemplatebackendGetUserResult
from openapi_client.models.templatebackend_reset_password_reply import TemplatebackendResetPasswordReply
from openapi_client.models.templatebackend_update_password_reply import TemplatebackendUpdatePasswordReply
from openapi_client.models.templatebackend_update_password_request import TemplatebackendUpdatePasswordRequest
from openapi_client.models.templatebackend_user import TemplatebackendUser
